[workspace]
members = [
    # 
    "bb8-nebula",
    # 
    "demos/tokio",
    # 
    "mobc-nebula",
    # 
    "nebula-client",
    # 
    "nebula-fbthrift/*",
    # 
    "serde-nebula-fbthrift-graph",
    # 
    "deserialize-nebula-fbthrift",
]
